-- CREATE TABLE FULL_ADDRESS(
--   ID SERIAL PRIMARY KEY NOT NULL,
--   STREET VARCHAR(100) NOT NULL,
--   STREET_NUMBER INT,
--   COMMUNE VARCHAR(100),
--   CITY VARCHAR(100) NOT NULL
-- );

-- 10 productos provistos por al menos un provecor y 5 ventas realizados al menos a un cleinte,
-- 4811069791
-- practica 2
-- Propuesta de proyecto final.


CREATE TABLE SUPPLIER(
  RUT VARCHAR(15) PRIMARY KEY UNIQUE,
  NAME VARCHAR(50) NOT NULL NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  WEB VARCHAR(100) NOT NULL,
  STREET VARCHAR(100) NOT NULL,
  STREET_NUMBER INT NOT NULL,
  COMMUNE VARCHAR(60) NOT NULL,
  CITY VARCHAR(60) NOT NULL
);

CREATE TABLE CLIENT(
  RUT VARCHAR(15) PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  STREET VARCHAR(100) NOT NULL,
  STREET_NUMBER INT NOT NULL,
  COMMUNE VARCHAR(60 NOT NULL,
  CITY VARCHAR(60) NOT NULL,
  WEB VARCHAR(100) NOT NULL,
  PHONE_NUMBER text[] NOT NULL,
);


CREATE TABLE PRODUCT(
 ID SERIAL PRIMARY KEY NOT NULL,
 NAME VARCHAR(50) NOT NULL,
 PRICE INT NOT NULL,
 STOCK SMALLINT NOT NULL,
 SUPPLIER_NAME VARCHAR(15) REFERENCES SUPPLIER(RUT),
 CATEGORY INT REFERENCES CATEGORY(ID)
);


CREATE TABLE CATEGORY(
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE SALE(
  ID SERIAL PRIMARY KEY NOT NULL,
  SALE_DATE DATE NOT NULL,
  CLIENT VARCHAR(15) REFERENCES CLIENT(RUT),
  DISCOUNT INT,
);
